CREATE TABLE `FAVORITE` (
  `CAT_NO` int(6) NOT NULL AUTO_INCREMENT,
  `MEM_NO` int(5) NOT NULL,
  PRIMARY KEY (`CAT_NO`, `MEM_NO`),
  KEY `MEM_NO` (`MEM_NO`),
  KEY `CAT_NO` (`CAT_NO`),
  CONSTRAINT `favorite_ibfk_1` FOREIGN KEY (`CAT_NO`) REFERENCES `CAT` (`CAT_NO`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `favorite_ibfk_2` FOREIGN KEY (`MEM_NO`) REFERENCES `MEMBER` (`MEM_NO`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;